apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openclaw-admin-dashboard
  labels:
    app.kubernetes.io/name: openclaw-admin-dashboard
spec:
  to:
    kind: Service
    name: openclaw-admin-dashboard
  port:
    targetPort: oauth
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
