apiVersion: v1
kind: ServiceAccount
metadata:
  name: openclaw-admin-dashboard
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.openclaw-admin-dashboard: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"openclaw-admin-dashboard"}}'
